config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins
  devise_for :members, :controllers => {
    :registrations => "members/registrations",
    :sessions => "members/sessions",
  }

  # ゲストユーザーログイン用のルート
  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_create'
  end

  namespace :admins do
    resources :articles, only: [:index, :show, :update, :destroy]
    resources :tweets, only: [:index, :show, :update, :destroy] do
      resources :tweet_comments, only: [:update, :destroy]
    end
    resources :members, only: [:index, :show, :update, :destroy] do
      get "following" => "members#follower", as: "following" #フォロー一覧
      get "followers" => "members#followed", as: "followers" #フォロワー一覧
      get "blocking" => "members#blocker", as: "blocking" #ブロックしているリスト一覧
      get "blockers" => "members#blocked", as: "blockers" #ブロックされているリスト一覧
    end
    resources :rooms, only: [:index, :update, :destroy] do
      resources :messages, only: [:update, :destroy]
    end
    resources :notices, only: [:index, :show, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :parts, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :members do
    resources :articles do
      resource :article_favorites, only: [:create, :destroy]
    end
    resources :tweets, only: [:index, :create, :show, :destroy] do
      resources :tweet_comments, only: [:create, :destroy] do
        resource :tweet_comment_favorites, only: [:create, :destroy]
      end
      resource :tweet_favorites, only: [:create, :destroy]
    end
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      resource :accesses, only: [:create]
      resource :blocks, only: [:create, :destroy]
      get "article_favorites" => "members#article_favorites", as: "article_favorites"
      get "cancel" => "members#cancel", as: "cancel" #退会確認画面表示
      patch "cancel" => "members#withdraw", as: "withdraw" #会員ステータス更新（退会する）
      get "following" => "relationships#follower", as: "following" #フォロー一覧
      get "followers" => "relationships#followed", as: "followers" #フォロワー一覧
      get "blocking" => "blocks#blocker", as: "blocking" #ブロックリスト一覧
      get "accesses" => "accesses#index", as: "accesses_index" #アクセス履歴一覧
    end
    resources :rooms, only: [:index, :show, :create]
    resource :notices, only: [:new, :create]
    resources :announces, only: :index

    # 訪れたメッセージルームの相手のメッセージルーム全てに既読をつける為（非同期通信）
    get "all_message_read" => "rooms#all_message_read", as: "all_message_read"

    get "top" => "articles#top", as: "top"

    constraints ->  request { request.session.try(:[], 'warden.user.member.key').try(:[], 0).try(:[], 0).present? } do
      # ログイン中のルートパス
      root to: "articles#index"
    end
    # 未ログイン時のルートパス
    root to: 'articles#top'
  end

  #市区町村のソートの為
  get "cities_select" => "searches#cities_select"
  get "cities_select_regist" => "searches#cities_select_regist"

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_members, dependent: :destroy
  has_many :members, through: :genre_members
  has_many :genre_articles, dependent: :destroy
  has_many :articles, through: :genre_articles

  enum status: { enable: true, disable: false }

  # バリデーションSTART------------------------------------------------------------------------------------------
  validates :name, presence: true, length: { maximum: 100 }
  # バリデーションEND--------------------------------------------------------------------------------------------

  # Gem kamirariの表示ページ数
  paginates_per 10

  # 最新順に並び替え
  default_scope -> { order(created_at: :desc)}
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < Admins::ApplicationController
  before_action :set_genre, only: [:edit, :update, :destroy]

  def index
    @genres = Genre.all
    @genres = @genres.page(params[:page])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path, notice: "ジャンルを追加しました"
    else
      flash.now[:alert] = "#{@genre.errors.count}件のエラーがあります"
      index
      render "index"
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to admins_genres_path, notice: "ジャンル情報を更新しました"
    else
      flash.now[:alert] = "#{@genre.errors.count}件のエラーがあります"
      render "edit"
    end
  end

  def destroy
    if @genre.destroy
      redirect_to admins_genres_path, notice: "ジャンルが削除されました"
    else
      redirect_to admins_genres_path, alert: "ジャンルの削除に失敗しました"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :status)
  end

  def set_genre
    @genre = Genre.find(params[:id])
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/_genre.html.erb
<tr>
  <td><%= genre.name %></td>
  <td><%= I18n.l(genre.created_at, format: :original) %></td>
  <td><%= I18n.l(genre.updated_at, format: :original) %></td>
  <td><%= link_to "編集", edit_admins_genre_path(genre), class: "btn btn-success", style: "color: white;" %></td>
  <td><%= render "layouts/status_form", { model: genre, action: admins_genre_path(genre) } %></td>
</tr>

app/views/admins/genres/edit.html.erb
<h2>ジャンル編集</h2>
<!-- バリデーションのエラーメッセージ -->
<%= render "/layouts/error_messages", model: @genre %>

<!-- ジャンル編集フォーム -->
<%= render "layouts/admin_add_form", { scope: :genre, model: @genre, action: admins_genre_path(@genre.id) } %>

app/views/admins/genres/index.html.erb
<h2>ジャンル一覧</h2>

<!-- バリデーションのエラーメッセージ -->
<%= render "/layouts/error_messages", model: @genre %>

<!-- ジャンル追加フォーム -->
<%= render "layouts/admin_add_form", { scope: :genre, model: Genre.new, action: admins_genres_path } %>

<table class="table table-hover table-inverse mt-3 bg-white">
  <thead class="thead-light">
    <tr>
      <th>ジャンル名</th>
      <th>登録日</th>
      <th>更新日</th>
      <th></th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody id="genre_lists">
    <%= render @genres %>
  </tbody>
</table>

<!-- もっと見るボタン -->
<%= render "layouts/and_more_button", { model: @genres } %>

app/views/admins/genres/index.js.erb
$("#genre_lists").append('<%= j(render @genres) %>');
$("#view_more").replaceWith("<%= j(link_to_next_page @genres, 'もっと見る', remote: true, id: 'view_more', class: "m-5 btn btn-primary", style: "color: white;") %>");