config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins
  devise_for :members, :controllers => {
    :registrations => "members/registrations",
    :sessions => "members/sessions",
  }

  # ゲストユーザーログイン用のルート
  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_create'
  end

  namespace :admins do
    resources :articles, only: [:index, :show, :update, :destroy]
    resources :tweets, only: [:index, :show, :update, :destroy] do
      resources :tweet_comments, only: [:update, :destroy]
    end
    resources :members, only: [:index, :show, :update, :destroy] do
      get "following" => "members#follower", as: "following" #フォロー一覧
      get "followers" => "members#followed", as: "followers" #フォロワー一覧
      get "blocking" => "members#blocker", as: "blocking" #ブロックしているリスト一覧
      get "blockers" => "members#blocked", as: "blockers" #ブロックされているリスト一覧
    end
    resources :rooms, only: [:index, :update, :destroy] do
      resources :messages, only: [:update, :destroy]
    end
    resources :notices, only: [:index, :show, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :parts, only: [:index, :create, :edit, :update, :destroy]
  end

  scope module: :members do
    resources :articles do
      resource :article_favorites, only: [:create, :destroy]
    end
    resources :tweets, only: [:index, :create, :show, :destroy] do
      resources :tweet_comments, only: [:create, :destroy] do
        resource :tweet_comment_favorites, only: [:create, :destroy]
      end
      resource :tweet_favorites, only: [:create, :destroy]
    end
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      resource :accesses, only: [:create]
      resource :blocks, only: [:create, :destroy]
      get "article_favorites" => "members#article_favorites", as: "article_favorites"
      get "cancel" => "members#cancel", as: "cancel" #退会確認画面表示
      patch "cancel" => "members#withdraw", as: "withdraw" #会員ステータス更新（退会する）
      get "following" => "relationships#follower", as: "following" #フォロー一覧
      get "followers" => "relationships#followed", as: "followers" #フォロワー一覧
      get "blocking" => "blocks#blocker", as: "blocking" #ブロックリスト一覧
      get "accesses" => "accesses#index", as: "accesses_index" #アクセス履歴一覧
    end
    resources :rooms, only: [:index, :show, :create]
    resource :notices, only: [:new, :create]
    resources :announces, only: :index

    # 訪れたメッセージルームの相手のメッセージルーム全てに既読をつける為（非同期通信）
    get "all_message_read" => "rooms#all_message_read", as: "all_message_read"

    get "top" => "articles#top", as: "top"

    constraints ->  request { request.session.try(:[], 'warden.user.member.key').try(:[], 0).try(:[], 0).present? } do
      # ログイン中のルートパス
      root to: "articles#index"
    end
    # 未ログイン時のルートパス
    root to: 'articles#top'
  end

  #市区町村のソートの為
  get "cities_select" => "searches#cities_select"
  get "cities_select_regist" => "searches#cities_select_regist"

end

app/controllers/admins/members_controller.rb
class Admins::MembersController < Admins::ApplicationController
  before_action :set_member, only: [:show, :update, :destroy]
  before_action :check_guest, only: [:destroy]

  def index
    @search_params = member_search_params
    @members = Member.search(@search_params)
    @members = @members.page(params[:page])
    @members = @members.includes([part_members: :part])
  end

  def show
    @member_tweets = @member.tweets
    @member_articles = @member.articles.page(params[:page])
    @member_articles = @member_articles.includes([:prefecture, part_articles: :part, genre_articles: :genre])
  end

  def update
    if @member.update(member_params)
      redirect_to request.referer, notice: "会員ステータスを更新しました"
    else
      redirect_to request.referer, alert: "会員ステータスの更新に失敗しました"
    end
  end

  def destroy
    if @member.destroy
      redirect_to admins_members_path, notice: "会員が削除されました"
    else
      redirect_to admins_members_path, alert: "会員の削除に失敗しました"
    end
  end

  def follower
    @members = Member.find(params[:member_id]).following_member
    @members = @members.includes([part_members: :part])
  end

  def followed
    @members = Member.find(params[:member_id]).follower_member
    @members = @members.includes([part_members: :part])
  end

  def blocker
    @members = Member.find(params[:member_id]).blocking_member
    @members = @members.includes([part_members: :part])
  end

  def blocked
    @members = Member.find(params[:member_id]).blocker_member
    @members = @members.includes([part_members: :part])
  end

  private
  def member_params
    params.require(:member).permit(:status)
  end

  def member_search_params
    params.fetch(:search, {}).permit(
      :name, :gender, :age_min, :age_max, :prefecture_id, { city_ids: [] },
      { part_ids: [] }, { genre_ids: [] }, { artists: [:name] }, :status)
  end

  def set_member
    @member = Member.find(params[:id])
  end

  def check_guest #ゲストユーザーの削除を禁止
    if @member.email == ENV["GUEST_LOGIN_USER_PASSWORD"]
      redirect_to request.referer, notice: "ゲストユーザーは削除できません"
    end
  end
end

app/controllers/members/accesses_controller.rb
class Members::AccessesController < Members::ApplicationController
  def index
    if params[:member_id].to_i == current_member.id
      @accesses = current_member.visited.includes(:visitor)
      @accesses = @accesses.page(params[:page])
      @accesses = @accesses.where.not(visitor_id: current_member.blocker_member)
    else
      redirect_to top_path, alert: "アクセスが拒否されました"
    end
  end

  def create
    unless params[:member_id].to_i == current_member.id
      current_member.visitor.create(visited_id: params[:member_id])
    end
  end
end

app/controllers/members/announces_controller.rb
class Members::AnnouncesController < ApplicationController
  def index
    Announce.where(checked: false).update_all(checked: true) #未読の通知を既読にする
    @announces = current_member.reciever.page(params[:page])
    @announces = @announces.includes([:article, :announcer, :reciever, tweet: :member, tweet_comment: :tweet, message: :room])
    @announces = @announces.where.not(announcer_id: current_member.blocker_member)
  end
end

app/controllers/members/application_controller.rb
class Members::ApplicationController < ApplicationController
  before_action :authenticate_member!
end

app/controllers/members/article_favorites_controller.rb
class Members::ArticleFavoritesController < Members::ApplicationController
  before_action :set_article

  def create
    article_favorite = current_member.article_favorites.new
    article_favorite.article_id = params[:article_id]
    if article_favorite.save
      flash.now[:notice] = "記事をお気に入りに追加しました"
      # 記事のお気に入り追加通知を作成
      Article.find(params[:article_id]).create_announce_article_favorite!(current_member)
    else
      flash.now[:alert] = "記事のお気に入り追加に失敗しました"
    end
  end

  def destroy
    article_favorite = current_member.article_favorites.find_by(article_id: params[:article_id])
    if article_favorite.destroy
      flash.now[:notice] = "記事をお気に入りから外しました"
    else
      flash.now[:alert] = "記事のお気に入り解除に失敗しました"
    end
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/members/articles_controller.rb
class Members::ArticlesController < Members::ApplicationController
  skip_before_action :authenticate_member!, only: [:top, :show, :about]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_member?, only: [:edit, :update, :destroy]
  before_action :blocked_member?, only: [:show]
  before_action :already_member_signed_in?, only: [:top]

  def top
    @search_params = article_search_params
    @articles = Article.search(@search_params).enable.opening
    @articles = @articles.where(member_id: Member.enable)
    @articles = @articles.page(params[:page])
    @articles = @articles.includes([:member, :prefecture, part_articles: :part, genre_articles: :genre])
  end

  def index
    @search_params = article_search_params
    @articles = Article.search(@search_params).enable.opening
    @articles = @articles.where(member_id: Member.enable)
    @articles = @articles.page(params[:page])
    @articles = @articles.includes([:member, :prefecture, part_articles: :part, genre_articles: :genre])
    @articles = @articles.where.not(member_id: current_member.blocker_member)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_member.articles.new(article_params)
    if @article.save
      redirect_to @article, notice: "記事が投稿されました"
    else
      flash.now[:alert] = "#{@article.errors.count}件のエラーが有ります"
      render "new"
    end
  end

  def show
    @part_articles = @article.part_articles.includes(:part)
    @genre_articles = @article.genre_articles.includes(:genre)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "記事が更新されました"
    else
      flash.now[:alert] = "#{@article.errors.count}件のエラーがあります"
      render "edit"
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path, notice: "記事が削除されました"
    else
      redirect_to articles_path, alert: "記事の削除に失敗しました"
    end
  end

  private
  def article_params
    params.require(:article).permit(
      :published_status, :category, :subject, :body, :prefecture_id, { city_ids: [] },
      :day_of_the_week, :band_intention, :music_intention, :gender, :age_min, :age_max,
      :sound, :band_theme, { part_ids: [] }, { genre_ids: [] })
  end

  def article_search_params
    params.fetch(:search, {}).permit(
      :published_status, :category, :subject, :body, :prefecture_id, { city_ids: [] },
      :day_of_the_week, :band_intention, :music_intention, :gender, :age_min, :age_max,
      :status, :band_theme, { part_ids: [] }, { genre_ids: [] })
  end

  def set_article
    @article = Article.find(params[:id])
    if @article.disable?
      redirect_to top_path, alert: "無効な記事です"
    elsif @article.close? && @article.member.id != current_member.id
      redirect_to top_path, alert: "非公開記事です"
    end
  end

  def signed_in_member? #ログインメンバー以外のアクセス、編集を禁止
    unless current_member.id == @article.member_id
      redirect_to top_path, alert: "アクセスが拒否されました"
    end
  end

  def blocked_member? # 会員が退会済、またはブロックされていればアクセスできない
    if @article.member.blocking?(current_member) || @article.member.disable?
      redirect_to top_path, alert: "アクセスできません"
    end
  end

  def already_member_signed_in? #ログインメンバーのアクセスを禁止
    if member_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/members/blocks_controller.rb
class Members::BlocksController < Members::ApplicationController
  before_action :set_member
  before_action :signed_in_member?, only: [:blocker]
  before_action :withdrawed_member?, only: [:create, :destroy, :blocker]

  def create
    current_member.block(params[:member_id])
    if current_member.following?(@member)
      current_member.unfollow(params[:member_id])
    end
   flash.now[:notice] = "#{@member.name}さんをブロックしました"
  end

  def destroy
    current_member.unblock(params[:member_id])
    flash.now[:notice] = "#{@member.name}さんのブロックを解除しました"
  end

  def blocker
    @members = @member.blocking_member
    @members = @members.where.not(id: current_member.blocker_member)
    @members = @members.page(params[:page])
    @members = @members.includes([part_members: :part])
  end

  private
  def set_member
    @member = Member.find(params[:member_id])
  end

  def signed_in_member? #ログインメンバー以外のアクセス、編集を禁止
    unless current_member.id == @member.id
      redirect_to top_path, alert: "アクセスが拒否されました"
    end
  end

  def withdrawed_member? # 会員が退会済であればブロック、アンブロックできない。アクセスもできない。
    if @member.disable?
      redirect_to top_path, alert: "アクセスできません"
    end
  end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/members_controller.rb
class Members::MembersController < Members::ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :article_favorites, :cancel, :withdraw]
  before_action :signed_in_member?, only: [:edit, :update, :article_favorites, :cancel, :withdraw]
  before_action :blocked_member?, only: [:show]
  before_action :check_guest, only: [:edit, :update, :cancel, :withdraw]

  def index
    @search_params = member_search_params
    @members = Member.search(@search_params).enable
    @members = @members.where.not(id: current_member.blocker_member)
    @members = @members.page(params[:page])
    @members = @members.includes([part_members: :part])
  end

  def show
    @member_tweets = @member.tweets.enable

    @member_articles = @member.articles.enable.opening
    @member_articles = @member_articles.page(params[:page])
    @member_articles = @member_articles.includes([:prefecture, part_articles: :part, genre_articles: :genre])

    # メッセージルーム関係START----------------------------------------------------------
    @current_member_entry = Entry.where(member_id: current_member.id)
    @member_entry = Entry.where(member_id: @member.id)
    if current_member.id != @member.id
      @current_member_entry.each do |cme|
        @member_entry.each do |me|
          if cme.room_id == me.room_id
            @is_room = true
            @room_id = cme.room_id
          end
        end
      end

      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
    # メッセージルーム関係END-----------------------------------------------------------
  end

  def edit
  end

  def update
    if @member.update(member_params)
      redirect_to @member, notice: "会員情報を更新しました"
    else
      flash.now[:alert] = "#{@member.errors.count}件のエラーがあります"
      render "edit"
    end
  end

  def article_favorites
    @favorited_articles = current_member.favorited_articles.enable.opening
    @favorited_articles = @favorited_articles.where.not(member_id: current_member.blocker_member)
    @favorited_articles = @favorited_articles.page(params[:page])
    @favorited_articles = @favorited_articles.includes([:member, :prefecture, part_articles: :part, genre_articles: :genre])
  end

  def cancel
  end

  def withdraw
    @member.update(member_params)
    if @member.disable?
      reset_session
      redirect_to top_path, notice: "退会しました"
    else
      redirect_to member_path(@member)
    end
  end

  private
  def member_params
    params.require(:member).permit(
      :name, :gender, :birthday, :address_prefecture, :address_city, :introduction,
      :sound, :profile_image, :email, :status, { part_ids: [] }, { genre_ids: [] },
      artists_attributes: [:id, :name])
  end

  def member_search_params
    params.fetch(:search, {}).permit(
      :name, :gender, :age_min, :age_max, :prefecture_id, { city_ids: [] },
      { part_ids: [] }, { genre_ids: [] }, { artists: [:name] }, :status)
  end

  def set_member
    if params[:member_id].nil?
      @member = Member.find(params[:id])
    else
      @member = Member.find(params[:member_id])
    end
  end

  def signed_in_member? #ログインメンバー以外のアクセス、編集を禁止
    unless current_member.id == @member.id
      redirect_to top_path, alert: "アクセスが拒否されました"
    end
  end

  def blocked_member? #会員が退会済、またはブロックされていればアクセスできない
    if @member.blocking?(current_member) || @member.disable?
      redirect_to top_path, alert: "アクセスできません"
    end
  end

  def check_guest #ゲストユーザーのみ機能制限
    if @member.email == ENV["GUEST_LOGIN_USER_PASSWORD"]
      redirect_to top_path, notice: "ゲストユーザーでは実行できません"
    end
  end
end

app/controllers/members/notices_controller.rb
class Members::NoticesController < Members::ApplicationController
  def new
    @notice = Notice.new

    if params[:tweet_id].present?
      @tweet = Tweet.find(params[:tweet_id])
      @tweet_flag = true
      @show_path = tweet_path(@tweet.id)
    elsif params[:tweet_comment_id].present?
      @tweet_flag = false
      @tweet = TweetComment.find(params[:tweet_comment_id])
      @show_path = tweet_tweet_comment_path(@tweet.tweet_id, @tweet.id)
    elsif params[:article_id].present?
      @article = Article.find(params[:article_id])
    end
  end

  def create
    @notice = current_member.notices.new(notice_params)

    if @notice.save
      redirect_to top_path, notice: "通報を投稿しました"
    else
      redirect_to request.referer, alert: "通報内容を入力してください"
    end
  end

  private
  def notice_params
    params.require(:notice).permit(:body, :tweet_id, :tweet_comment_id, :article_id)
  end
end

app/views/members/members/_article_lists.html.erb
<div class="row">
  <% member_articles.each do |article| %>
    <div class="col-lg-6">
      <div class="row">
        <!-- 管理者としてログインしている場合は管理者側のパスをパーシャルに渡す -->
        <% if admin_signed_in? %>
          <%= render partial: "members/articles/article", locals: { article: article, article_path: admins_article_path(article.id) } %>
        <% else %>
          <%= render partial: "members/articles/article", locals: { article: article, article_path: article_path(article.id) } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/members/members/_member_lists.html.erb
<% members.each do |member| %>
  <div class="col-lg-6">
    <div class="row">
      <%= render partial: "members/members/member", locals: { member: member, member_path: member_path(member.id) } %>
    </div>
  </div>
<% end %>

app/views/members/members/article_favorites.js.erb
$("#favorited_article_lists").append('<%= j(render "members/articles/article_lists", { articles: @favorited_articles }) %>');
$("#view_more").replaceWith("<%= j(link_to_next_page @favorited_articles, 'もっと見る', remote: true, id: 'view_more', class: "m-5 btn btn-primary", style: "color: white;") %>");

app/views/members/members/cancel.html.erb
<h1>本当に退会しますか？</h1>

<%= form_with model: @member, url: member_withdraw_path(@member), local: true do |f| %>
  <div class="field">
    <%= f.hidden_field :status, value: :disable %>
    <%= f.submit "退会する", class: "actions btn btn-danger" %>
  </div>
<% end %>

app/views/members/members/show.html.erb
<!-- 足跡機能START -->
<script>
  $(document).ready(function() {
    $("#create_access").trigger('click');
  });
</script>

<!-- 管理者としてログイン中の場合は除く -->
<% unless admin_signed_in? %>
  <%= form_with model: Access.new, url: member_accesses_path(@member) do |f| %>
    <%= f.submit "", style: "display: none", id: "create_access" %>
  <% end %>
<% end %>
<!-- 足跡機能END -->

<!-- 自分のページ、管理者としてログインしていない場合 -->
<% if @member == current_member && admin_signed_in? == false %>
  <h2>マイページ</h2>
<% else %>
  <h2><%= @member.name %>さんのページ</h2>
<% end %>

<div class="row ProfileWrap">
  <!-- プロフィールエリア（画面左半分） -->
  <div class="col-lg-6 pr-3 mb-5">
    <h3 class="mb-5">プロフィール</h3>
    <div class="row justify-content-start mb-2">
      <%= render "members/member_histries/online_members", { member: @member } %>
    </div>
    <div class="row ShowProfImg">
      <%= attachment_image_tag @member, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: 300 %>
    </div>
    <!-- 管理者としてログイン中の場合は除く -->
    <% unless admin_signed_in? %>
      <!-- フォロー・アンフォローボタン＋ブロック・アンプロックボタン -->
      <div class="row mt-3 mt-4 mb-4">
        <span id="relation-member-<%= @member.id %>" class="mr-3">
          <%= render "members/relationships/follow_button", { member: @member } %>
        </span>
        <span id="block-member-<%= @member.id %>">
          <%= render "members/blocks/block_button", { member: @member } %>
        </span>
      </div>
    <% end %>

    <!-- フォロー・フォロワー一覧へのリンク -->
    <div class="row mt-3 mb-4">
      <div class="btn btn-warning">
        <% if admin_signed_in? %>
          <%= link_to admins_member_following_path(@member), class: "FollowerButton" do %>
            フォロー x <%= @member.following_member.count %>
          <% end %>
        <% else %>
          <%= link_to member_following_path(@member), class: "FollowerButton" do %>
            フォロー x <%= @member.following_member.count %>
          <% end %>
        <% end %>
      </div>
      <div class="btn btn-warning ml-2">
        <% if admin_signed_in? %>
          <%= link_to admins_member_followers_path(@member), class: "FollowedButton" do %>
            フォロワー x <%= @member.follower_member.count %>
          <% end %>
        <% else %>
          <%= link_to member_followers_path(@member), class: "FollowedButton" do %>
            フォロワー x <%= @member.follower_member.count %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row mb-5">
      <% if admin_signed_in? %>
        <%= link_to "ブロックリスト", admins_member_blocking_path(@member) %>
        <%= link_to "ブロッカーリスト", admins_member_blockers_path(@member) %>
      <% else %>
        <!-- ログイン中メンバー自分自身の場合 -->
        <% if @member == current_member %>
          <%= link_to "", member_accesses_path(@member), class: "fas fa-shoe-prints fa-2x" %>
          <%= link_to "", member_article_favorites_path(current_member.id), class: "fa fa-star fa-2x faa-wrench animated-hover-item" %>
          <%= link_to "", edit_member_path, class: "fas fa-user-edit fa-2x" %>
          <%= link_to "", member_blocking_path(@member), class: "fas fa-user-slash fa-2x" %>
          <%= link_to "", member_cancel_path(@member), class: "fas fa-user-times fa-2x" %>
        <% else %>
          <% if @is_room %>
            <%= link_to "メッセージルームへ", room_path(@room_id), class: "btn-gradient-radius" %>
          <% else %>
            <%= form_with model: @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :member_id, value: @member.id %>
              <% end %>
              <%= f.submit "メッセージルームを作る", class: "btn-gradient-radius mb-5" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <!-- メンバー情報エリア -->
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:name) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= @member.name %>
      </div>
    </div>
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:gender) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= Member.human_attribute_name("gender.#{@member.gender}") %>
      </div>
    </div>
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:birthday) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= @member.birthday.strftime("%Y年%-m月%-d日") %>
      </div>
    </div>
    <h3 class="mt-3">
      <small>年齢</small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= @member.age %><span>歳</span>
      </div>
    </div>
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:address_prefecture) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= @member.address_prefecture %>
      </div>
    </div>
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:address_city) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= @member.address_city %>
      </div>
    </div>

    <h3 class="mt-3">
      <small>担当<%= Part.model_name.human %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <% part_member_name = "" %>
        <% @member.part_members.includes(:part).each do |part_member| %>
          <% part_member_name = part_member_name + part_member.part.name + ", " %>
        <% end %>
        <%= part_member_name.chop.chop %>
      </div>
    </div>
    <h3 class="mt-3">
      <small>好きな<%= Genre.model_name.human %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <% genre_member_name = "" %>
        <% @member.genre_members.includes(:genre).each do |genre_member| %>
          <% genre_member_name = genre_member_name + genre_member.genre.name + ", " %>
        <% end %>
        <%= genre_member_name.chop.chop %>
      </div>
    </div>
    <h3 class="mt-3">
      <small>好きな<%= Artist.model_name.human %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <% artist_name = "" %>
        <% @member.artists.each do |artist| %>
          <% unless artist.name.empty? %>
            <% artist_name = artist_name + artist.name + ", " %>
          <% end %>
        <% end %>

        <% if artist_name.empty? %>
          <span>指定はありません</span>
        <% else %>
          <%= artist_name.chop.chop %>
        <% end %>
      </div>
    </div>
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:introduction) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= simple_format(@member.introduction) %>
      </div>
    </div>
    <h3 class="mt-3">
      <small>登録日時</small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2 pl-5">
        <%= I18n.l(@member.created_at, format: :original) %>
      </div>
    </div>
    <h3 class="mt-3">
      <small><%= Member.human_attribute_name(:sound) %></small>
    </h3>
    <div class="row">
      <div class="col-lg-12 mx-auto mb-2">
        <% if @member.sound.blank? %>
          <span>音源はありません</span>
        <% else %>
          <iframe width="100%" height="315" src="https://www.youtube.com/embed/<%= @member.sound.last(11) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
      </div>
    </div>
  </div>
  <!-- メンバーのタイムラインエリア（画面右半分） -->
  <div class="col-lg-6 mb-5">
    <div class="row ml-3">
      <h3 class="mb-4">タイムライン</h3>
      <% if @member_tweets.exists? %>
        <div class="twitter__container">
          <div class="twitter__title">
            <span class="twitter-logo">♬</span>
          </div>
          <div class="twitter__contents scroll" id="tweets">
            <!-- ツイート一覧 -->
            <%= render "members/tweets/tweet_lists", { tweets: @member_tweets }  %>
          </div>
        </div>
      <% else %>
        <h4 class="mt-5">ツイートはありません</h4>
      <% end %>
    </div>
  </div>
</div>

<!-- バンド記事一覧 -->
<h3 class="">バンド記事一覧</h3>
<div class="row">
  <% if @member_articles.exists? %>
    <!-- 記事一覧 -->
    <div id="member_article_lists" class="col-lg-12">
      <!-- kaminariでページネーションのため部分テンプレート化 -->
      <%= render "members/members/article_lists", { member_articles: @member_articles } %>
    </div>
  <% else %>
    <h4 class="mt-3 ml-5 mb-5">投稿記事はありません</h4>
  <% end %>
</div>

<!-- もっと見るボタン -->
<%= render "layouts/and_more_button", { model: @member_articles } %>